/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.AluguelDAO;
import DAO.ClienteDAO;
import DAO.VeiculoDAO;
import DTO.AluguelDTO;
import DTO.ClienteDTO;
import DTO.VeiculoDTO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MuriloCalmon
 */
public class CadastrarAluguel extends javax.swing.JFrame {
private static CadastrarAluguel instancia=null;
    /**
     * Creates new form CadastrarAluguel
     */
    public CadastrarAluguel() {
        initComponents();
        wizard.setSelectedIndex(0);
       // setLocation(400,100);
    }
    public static CadastrarAluguel getIntancia(){
        if(instancia==null)
            instancia = new CadastrarAluguel();
        return instancia;
    }
    private void limpar(){
        String texto = " ";
        
        txtnome.setText(texto);
        txtCpf.setText(null);
        txtIdVeiculo.setText(texto);
        txtIdPlaca.setText(texto);
        txtveiculo.setText(texto);
        FtxtDataAluguel.setText(texto);
        FtxtDataEntrega.setText(texto);
        txtEntregue.setText(texto);
        txtObservacao.setText(texto);
        txtValor.setText(texto);
        
    }
     public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTCliente.getModel();
        modelo.setNumRows(0);
        ClienteDAO cdao = new ClienteDAO();

        for (ClienteDTO c : cdao.read()) {

            modelo.addRow(new Object[]{
                c.getNomeCliente(),
                c.getEndereco(),
                c.getUf(),
                c.getTelefone(),
                c.getCpf(),
                c.getEmail()

            });

        }

    }
      public void readJTableV() {
        DefaultTableModel modelo = (DefaultTableModel) jTVeiculos.getModel();
        modelo.setNumRows(0);
        VeiculoDAO cdao = new VeiculoDAO();

        for (VeiculoDTO v : cdao.read()) {

            modelo.addRow(new Object[]{
                v.getPlaca(),
                v.getAnoModelo(),
                v.getQtdPortas(),
                v.getAcessorios(),
                v.getId_fabricante(),
                v.getId_modelo(),
                v.getId_veiculo(),
                v.getDisponivel(),
                
                

            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wizard = new javax.swing.JTabbedPane();
        p1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVeiculos = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        txtnome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtveiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdVeiculo = new javax.swing.JTextField();
        txtIdPlaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FtxtDataAluguel = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FtxtDataEntrega = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEntregue = new javax.swing.JTextField();
        txtObservacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdisponivel = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Aluguel");

        p1.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClickk(evt);
            }
        });

        jTCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereco", "UF", "Telefone", "CPF", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClienteMouseClick(evt);
            }
        });
        jTCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTClienteviewClientes(evt);
            }
        });
        jScrollPane2.setViewportView(jTCliente);

        jButton1.setText("Atualizar Tabelas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Próximo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irparap2(evt);
            }
        });

        jButton5.setText("Lista de Alugueis");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5MostrarListaAlu(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5)))
        );

        wizard.addTab("Cliente", p1);

        p2.setBackground(new java.awt.Color(204, 204, 255));

        jTVeiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Ano", "Nº Portas", "Acessórios", "Fabricante", "Modelo", "Número", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVeiculosMouseClickVeiculos(evt);
            }
        });
        jTVeiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTVeiculosViewVeiculos(evt);
            }
        });
        jScrollPane1.setViewportView(jTVeiculos);

        jButton6.setText("Anterior");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarParaP1(evt);
            }
        });

        jButton7.setText("Próximo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irparap3(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(27, 27, 27)
                .addComponent(jButton7)
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)))
        );

        wizard.addTab("Veículo", p2);

        p3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Nome do cliente");

        jLabel2.setText("CPF");

        jLabel3.setText("Veiculo");

        jLabel4.setText("Número");

        jLabel5.setText("Placa");

        jLabel6.setText("Data do Aluguel");

        jLabel7.setText("Data de Entrega");

        jLabel8.setText("Entregue");

        jLabel9.setText("OBS:");

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ClickCadastrar(evt);
            }
        });

        jLabel10.setText("Valor a ser pago:");

        jLabel11.setText("disponivel");

        jButton9.setText("Anterior");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarP2(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtIdPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FtxtDataAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FtxtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(47, 47, 47)
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(250, Short.MAX_VALUE))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p3Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel2))
                                    .addGroup(p3Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addContainerGap())
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FtxtDataAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FtxtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton2)))))
        );

        wizard.addTab("Concluir Aluguel", p3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wizard)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wizard)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTVeiculosMouseClickVeiculos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVeiculosMouseClickVeiculos
        // TODO add your handling code here:
        if (jTVeiculos.getSelectedRow() != -1) {

            txtIdPlaca.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 0).toString());
            //txtAno.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 1).toString());
            //txtPorta.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 2).toString());
            //txtAcessorio.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 3).toString());
            //txtFabricante.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 4).toString());
            txtveiculo.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 5).toString());
            txtIdVeiculo.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 6).toString());
            txtdisponivel.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 7).toString());
            

        }
    }//GEN-LAST:event_jTVeiculosMouseClickVeiculos

    private void jTVeiculosViewVeiculos(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTVeiculosViewVeiculos
        // TODO add your handling code here:
        if (jTVeiculos.getSelectedRow() != -1) {

            txtIdPlaca.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 0).toString());
            //txtAno.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 1).toString());
            //txtPorta.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 2).toString());
            //txtAcessorio.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 3).toString());
           // txtFabricante.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 4).toString());
            txtveiculo.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 5).toString());
            txtIdVeiculo.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 6).toString());

        }
    }//GEN-LAST:event_jTVeiculosViewVeiculos

    private void jTClienteMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClienteMouseClick
        // TODO add your handling code here:
        if (jTCliente.getSelectedRow() != -1) {
            
            txtnome.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 0).toString());
           // txtEndereco.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 1).toString());
            //txtUf.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 2).toString());
            //txtTelefone.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 3).toString());
            txtCpf.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 4).toString());
            //txtEmail.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_jTClienteMouseClick

    private void jTClienteviewClientes(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClienteviewClientes
        // TODO add your handling code here:
        if (jTCliente.getSelectedRow() != -1) {

            txtnome.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 0).toString());
           // txtEndereco.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 1).toString());
            //txtUf.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 2).toString());
            //txtTelefone.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 3).toString());
            txtCpf.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 4).toString());
            //txtEmail.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_jTClienteviewClientes

    private void jScrollPane2MouseClickk(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClickk
        // TODO add your handling code here:
        if (jTCliente.getSelectedRow() != -1) {

            txtnome.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 0).toString());
           // txtEndereco.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 1).toString());
            //txtUf.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 2).toString());
            //txtTelefone.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 3).toString());
            txtCpf.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 4).toString());
            //txtEmail.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_jScrollPane2MouseClickk

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        readJTable();
        readJTableV();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ClickCadastrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ClickCadastrar
        // TODO add your handling code here:
        AluguelDTO a =  new AluguelDTO();
        AluguelDAO dao = new AluguelDAO();
        VeiculoDTO v = new VeiculoDTO();
        VeiculoDAO vdao = new VeiculoDAO();
        
        v.setPlaca(txtIdPlaca.getText());
    
        if(vdao.disponivel(txtIdPlaca.getText())){
            
            
            
            a.setVeiculo(txtveiculo.getText());
            a.setDataAluguel(FtxtDataAluguel.getText());
            a.setDataEntrega(FtxtDataEntrega.getText());
            a.setCliente(txtnome.getText());
            a.setEntregue(txtEntregue.getText());
            a.setObservação(txtObservacao.getText());
            a.setValorPago(txtValor.getText());
            dao.create(a,v);
            
            limpar();
        }else{
            JOptionPane.showMessageDialog(null, "Veículo indisponivel!");
        }
    
    }//GEN-LAST:event_jButton2ClickCadastrar

    private void jButton5MostrarListaAlu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5MostrarListaAlu
        // TODO add your handling code here:
        ListaAluguel.getIntancia().setVisible(true);
    }//GEN-LAST:event_jButton5MostrarListaAlu

    private void irparap2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irparap2
        // TODO add your handling code here:
        wizard.setSelectedIndex(1);
    }//GEN-LAST:event_irparap2

    private void VoltarParaP1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarParaP1
        // TODO add your handling code here:
        wizard.setSelectedIndex(0);
    }//GEN-LAST:event_VoltarParaP1

    private void irparap3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irparap3
        // TODO add your handling code here:
        wizard.setSelectedIndex(2);
    }//GEN-LAST:event_irparap3

    private void VoltarP2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarP2
        // TODO add your handling code here:
        wizard.setSelectedIndex(1);
    }//GEN-LAST:event_VoltarP2

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtDataAluguel;
    private javax.swing.JFormattedTextField FtxtDataEntrega;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTCliente;
    private javax.swing.JTable jTVeiculos;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEntregue;
    private javax.swing.JTextField txtIdPlaca;
    private javax.swing.JTextField txtIdVeiculo;
    private javax.swing.JTextField txtObservacao;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtdisponivel;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtveiculo;
    private javax.swing.JTabbedPane wizard;
    // End of variables declaration//GEN-END:variables
}
