/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Telas;

import DAO.AluguelDAO;
import DAO.VeiculoDAO;
import DTO.AluguelDTO;
import DTO.VeiculoDTO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MuriloCalmon
 */
public class ListaAluguel extends javax.swing.JFrame {
 private static ListaAluguel instancia =null;
    /** Creates new form ListaAluguel */
    public ListaAluguel() {
        initComponents();
    }
    public static ListaAluguel getIntancia(){
        if(instancia==null)
            instancia = new ListaAluguel();
        return instancia;
    }
         public void ViewJtable() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTAluguel.getModel();
        jTAluguel.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
      public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTAluguel.getModel();
        modelo.setNumRows(0);
        AluguelDAO adao = new AluguelDAO();

        for (AluguelDTO a : adao.read()) {

            modelo.addRow(new Object[]{
                a.getVeiculo(),
                a.getDataAluguel(),
                a.getDataEntrega(),
                a.getCliente(),
                a.getEntregue(),
                a.getObservação(),
                a.getValorPago(),
                a.getId_aluguel(),
                
                

            });

        }

    }
            public void readJTableV() {
        DefaultTableModel modelo = (DefaultTableModel) jTVeiculos.getModel();
        modelo.setNumRows(0);
        VeiculoDAO cdao = new VeiculoDAO();
        

        for (VeiculoDTO v : cdao.read()) {

            modelo.addRow(new Object[]{
                v.getPlaca(),
                v.getAnoModelo(),
                v.getQtdPortas(),
                v.getAcessorios(),
                v.getId_fabricante(),
                v.getId_modelo(),
                v.getId_veiculo(),
                //v.getDisponivel(),
                
                

            });
            

        }

    }
      private void limpar(){
        String texto = " ";
       // txtIdModelo1.setText(texto);
        txtveiculo.setText(texto);
        FtxtDataAluguel.setText(texto);
        FtxtDataEntrega.setText(texto);
        txtCliente.setText(texto);
        txtEntregue.setText(texto);
        txtObservacao.setText(texto);
        txtValor.setText(texto);
        txtid_aluguel.setText(texto);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTVeiculos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAluguel = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtid_aluguel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEntregue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FtxtDataAluguel = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        FtxtDataEntrega = new javax.swing.JFormattedTextField();
        txtObservacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtveiculo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTVeiculos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Ano", "Nº Portas", "Acessórios", "Fabricante", "Modelo", "Número", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTVeiculos);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Aluguel");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTAluguel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTAluguel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Veículo", "Data do Aluguel", "Data da Entrega", "cliente", "Entregue", "Observação", "Valor a ser Pago", "Id_aluguel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClick(evt);
            }
        });
        jTAluguel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ViewTableAlu(evt);
            }
        });
        jScrollPane1.setViewportView(jTAluguel);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Devolução");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickExcluir(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Atualizar Dados");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickAtualizar(evt);
            }
        });

        jLabel5.setText("Nome do Cliente");

        jLabel1.setText("Id_aluguel");

        jLabel2.setText("Veículo");

        jLabel6.setText("Entregue");

        jLabel3.setText("Data do Aluguel");

        jLabel4.setText("Data de Entrega");

        jLabel7.setText("OBS:");

        jLabel8.setText("Valor a ser pago:");

        jButton1.setText("Atualizar Tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FtxtDataAluguel))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FtxtDataEntrega))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtid_aluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(txtveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(txtEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FtxtDataAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FtxtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid_aluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtObservacao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTableAlu(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ViewTableAlu
        // TODO add your handling code here:
          if (jTAluguel.getSelectedRow() != -1) {
          
        txtveiculo.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 0).toString());
        FtxtDataAluguel.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 1).toString());
        FtxtDataEntrega.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 2).toString());
        txtCliente.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 3).toString());
        txtEntregue.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 4).toString());
        txtObservacao.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 5).toString());
        txtValor.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 6).toString());
        txtid_aluguel.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 7).toString());
        //txtIdModelo1.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 5).toString());
        
    }//GEN-LAST:event_ViewTableAlu
    }
    private void MouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClick
        // TODO add your handling code here:
           if (jTAluguel.getSelectedRow() != -1) {
        txtveiculo.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 0).toString());
        FtxtDataAluguel.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 1).toString());
        FtxtDataEntrega.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 2).toString());
        txtCliente.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 3).toString());
        txtEntregue.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 4).toString());
        txtObservacao.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 5).toString());
        txtValor.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 6).toString());
        txtid_aluguel.setText(jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 7).toString());
        //txtIdModelo1.setText(jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 5).toString());
        
    }
    }//GEN-LAST:event_MouseClick

    private void ClickExcluir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickExcluir
        // TODO add your handling code here:
         if (jTAluguel.getSelectedRow() != -1) {
            AluguelDTO a = new AluguelDTO();
            AluguelDAO dao = new AluguelDAO();
              
            
             
                 a.setId_aluguel(txtid_aluguel.getText());
                 dao.devolver(a);
                 
            
            a.setId_aluguel((String) jTAluguel.getValueAt(jTAluguel.getSelectedRow(), 7));

            dao.delete(a);
            //this.setVisible(false);
       


         }    readJTable();
        
    }//GEN-LAST:event_ClickExcluir

    private void ClickAtualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickAtualizar
        // TODO add your handling code here:
        if (jTAluguel.getSelectedRow() != -1) {

            AluguelDTO a = new AluguelDTO();
            AluguelDAO dao = new AluguelDAO();


        a.setVeiculo(txtveiculo.getText());
        a.setDataAluguel(FtxtDataAluguel.getText());
        a.setDataEntrega(FtxtDataEntrega.getText());
        a.setCliente(txtCliente.getText());
        a.setEntregue(txtEntregue.getText());
        a.setObservação(txtObservacao.getText());
        a.setValorPago(txtValor.getText());
        a.setId_aluguel(txtid_aluguel.getText());
        //v.setId_modelo(txtIdModelo1.getText());
       
            dao.update(a);

            readJTable();
            limpar();
        }
    }//GEN-LAST:event_ClickAtualizar

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtDataAluguel;
    private javax.swing.JFormattedTextField FtxtDataEntrega;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTAluguel;
    private javax.swing.JTable jTVeiculos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtEntregue;
    private javax.swing.JTextField txtObservacao;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtid_aluguel;
    private javax.swing.JTextField txtveiculo;
    // End of variables declaration//GEN-END:variables

}
